services:
  kafka:
    build: .          # ruta al Dockerfile
    container_name: kafka-broker
    networks: [vault-net]
    environment:
      NODE_ID:        "0"
      ADVERTISED_HOST: "kafka"     # nombre de servicio DNS interno
      CONTROLLER_QUORUM_VOTERS: "0@kafka:9094"
    volumes:
      - broker-auth:/vault         # role_id y secret_id
      - kafka-data:/var/lib/kafka/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/opt/kafka/bin/kafka-topics.sh",
             "--bootstrap-server","kafka:9093",
             "--command-config","/opt/kafka/config/manual/server.properties",
             "--list"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  vault-net:
    external: true
    name: stage-compose_default  # misma red que Vault

volumes:
  broker-auth:
    external: true
    name: stage-compose_broker-auth
  kafka-data:
