services:
  kafka:
    build: ../kafka-broker-mtls
    container_name: kafka
    ports:
      - "9093:9093"
    volumes:
      - ../certs:/certs:ro          # root CA
      - broker-auth:/vault       # role_id & secret_id
    networks:
      - vault-net                   # misma red que Vault

networks:
  vault-net:
    external: true
    name: stage-compose_default     # ya creada por Stage 2

volumes:
  broker-auth:
