services:
  kafka:
    build: ../kafka-broker-mtls
    container_name: kafka-broker

    networks:
      vault-net:               # ⬅️  SAME network
        aliases:               # ⬅️  NUEVO
          - srv1.broker.kafka  #     ← el CN/SAN que aparece en el cert

    environment:
      NODE_ID: "0"
      ADVERTISED_HOST: "srv1.broker.kafka"   # ← pon el mismo alias
      CONTROLLER_QUORUM_VOTERS: "0@srv1.broker.kafka:9094"

    volumes:
      - broker-auth:/vault
      - kafka-data:/var/lib/kafka/data

    restart: unless-stopped

    healthcheck:               # usa el alias para evitar el mismo error
      test: ["CMD",
             "/opt/kafka/bin/kafka-topics.sh",
             "--bootstrap-server", "srv1.broker.kafka:9093",
             "--command-config", "/opt/kafka/config/manual/server.properties",
             "--list"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  vault-net:
    external: true
    name: stage-compose_default

volumes:
  broker-auth:
    external: true
    name: stage-compose_broker-auth
  kafka-data:
