
services:
  kafka:
    build: ../kafka-broker-mtls
    depends_on:
      - vault
    ports:
      - "9093:9093"
    volumes:
      - ../certs:/certs
      - broker-auth:/vault
    networks:
      - vault-net   # <—

networks:
  vault-net:
    external: true
    name: stage-compose_default  # <— red ya creada por Stage 2

volumes:
  broker-auth:
