
services:
  kafka:
    build: ../kafka-broker-mtls
    depends_on:
      - vault                       # servicio de Stage 2
    ports:
      - "9093:9093"
    volumes:
      - ../certs:/certs             # rootCA.pem
      - broker-auth:/vault          # role_id & secret_id

networks:
  default:
    external: true
    name: stage-compose_default     # comparte red con Vault

volumes:
  broker-auth:
