services:
  kafka-client:
    build: ../kafka-client-mtls   # <- donde pongas el Dockerfile y el start.sh
    depends_on: [vault]
    environment:
      VAULT_ADDR: http://vault:8200
    volumes:
      - broker-auth:/vault
      - ./certs:/certs
      - ./client:/client
