services:
  kafka-client:
    build:
      context: ../kafka-client-mtls
      dockerfile: Dockerfile
    container_name: kafka-client
    volumes:
      - ../kafka-client-mtls/certs:/certs            # rootCA.pem
      - ./certs:/output           # donde el agent escribe client.pem
      - broker-auth:/vault        # role_id / secret_id
    networks:
      - vault-net
    # abre shell, para que puedas probar manualmente:
    command: ["bash"]

networks:
  vault-net:
    external: true
    name: stage-compose_default

volumes:
  broker-auth:
    external: true
    name: stage-compose_broker-auth
